trigger:
  branches:
    include:
      - main  # ✅ Cambia esto si tu rama principal se llama diferente (como "master")

pool:
  vmImage: 'ubuntu-latest'  # 🧠 Usamos una máquina Ubuntu para correr el pipeline

variables:
  AZURE_WEBAPP_NAME: 'bidvisor-app'  # ✅ Cambia esto por el nombre de tu App Service en Azure
  AZURE_RESOURCE_GROUP: 'DocuMind'  # ✅ Cambia esto por el nombre de tu grupo de recursos

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'  # ✅ Cambia si usas otra versión de Python (debe coincidir con tu App Service)

- script: |
    python -m venv env
    source env/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'  # 🧠 Instala dependencias necesarias

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'  # ✅ Cambia esto por el nombre de tu "Service Connection"
    appName: '$(AZURE_WEBAPP_NAME)'       # 🧠 Se usa lo de arriba
    package: '$(Pipeline.Workspace)/drop/app.zip'
