name: Azure Web App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "1. Checkout repository"
        uses: actions/checkout@v3

      - name: "2. Setup Python 3.12"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: "3. Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "4. (Opcional) Run tests"
        run: |
          # pytest --maxfail=1 --disable-warnings -q
          echo "No hay tests configurados"

      - name: "5. Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: bidvisor-gha
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: "6. URL deployment"
        run: echo "✅ App desplegada en https://bidvisor-gha.azurewebsites.net"
